### ISSUE TITLE
TODO: Add Adusumulli melt rates as an example. 

### ISSUE THREAD

**Issue by jkingslake** [ldeo-glaciology/pangeo-glaciology-examples#2]

**Comment by jkingslake** [comment]
using https://github.com/ldeo-glaciology/pangeo_ADmeltrates as a starting point

**Comment by jkingslake** [comment]
this has been started, but the notebook needs tidying up.

**Comment by porterdf** [comment]
@jkingslake pushed some small changes to test our workflow
