### ISSUE TITLE
TODO: rerun the builderbot action

### ISSUE THREAD

**Issue by jkingslake** [ldeo-glaciology/pangeo-glaciology-examples#4]
The builderbot action fails at the "trigger repository dispatch on Pangeo Gallery" stage meaning that it is running the notebook ok. I think I just need to re-run the action once this [pull request](https://github.com/pangeo-gallery/pangeo-gallery/pull/53#issue-574528130) in the pangeo-gallery repo has been accepted.

**Comment by rabernat** [comment]
You actually don't have to rerun it! http://gallery.pangeo.io/repos/ldeo-glaciology/pangeo-glaciology-examples/01_bedmachine.html 🎉 

But from now on, the workflow should run without error.

I'm impressed you got this all working with no help. It's a bit of a house of cards! But it is actually very powerful.

**Comment by jkingslake** [comment]
Oh perfect, thanks! Yeah it seems really powerful. 
[These](http://gallery.pangeo.io/contributing.html) are good instructions. 
Thanks again!
